# Workflow name
name: 'Chromatic'

# Event for the workflow
on:
  push:
    branches:
      - feature/ui
    paths:
      - .github/workflows/chromatic.yml
      - packages/mui-theme/**
      - apps/design-system/**

# List of jobs
jobs:
  chromatic-deployment:
    # Operating System
    runs-on: ubuntu-latest
    # Job steps
    steps:
      - uses: actions/checkout@v1
      - name: Install dependencies
        run: yarn
      - name: Build @lunit/mui-theme package
        run: yarn build:mui-theme
      - name: Publish to Chromatic
        uses: chromaui/action@v1
        with:
          workingDir: 'apps/design-system'
          token: ${{ secrets.GITHUB_TOKEN }}
          projectToken: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}